## M.FAHAD FAROOQ 

# NUMPY INDEXING AND SELECTION :

In [1]:
import numpy as np

In [2]:
arr=np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [5]:
arr[4]

4

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
slic=arr[:5]

In [8]:
slic

array([0, 1, 2, 3, 4])

# How Numpy Array Differ From Python List :

## Numpy Is Different From Pyhton List Because Of Its Broadcasting Behaviour

In [9]:
slic[:5]=100

In [10]:
slic

array([100, 100, 100, 100, 100])

### See Due to its Boradcasting Behaviour its also changes the Orignal Array   As well as Slic Array 

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

### But This Boradcast will not affect the Copy Array See :

In [12]:
copy_arr=arr.copy()

In [13]:
copy_arr


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
copy_arr[:]=200

In [15]:
copy_arr

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

#### See The Orignal Array Got Un-Affected :

In [16]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## Creating 2d Array and Some Indexing Func : 

In [18]:
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [19]:
arr1


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### DOUBLE BRACKET METHOD TO GRAB  ANY ELEMENT FROM ARRAY 

In [24]:
arr1[0][3]

4

In [25]:
arr1[1][2]

7

In [26]:
arr1[2][0]

9

#### SINGLE BRACKET METHOD TO GRAB  ANY ELEMENT FROM ARRAY 

In [27]:
arr1[0,3]

4

In [28]:
arr1[1,2]

7

In [29]:
arr1[2,0]

9

### SLICING METHOD TO GRAB CHUNK OF ARRAY  

In [30]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
arr1[:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [32]:
arr1[0:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [34]:
bool_arr=arr1>5

In [35]:
bool_arr

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [39]:
arr1[bool_arr]                       #it will give only those values which are correct 

array([ 6,  7,  8,  9, 10, 11, 12])

# NUMPY OPERATIONS 

In [40]:
arr1=np.arange(11,22)

In [41]:
arr1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [42]:
arr1*arr

array([1100, 1200, 1300, 1400, 1500,   80,  102,  126,  152,  180,  210])

In [43]:
arr1-arr

array([-89, -88, -87, -86, -85,  11,  11,  11,  11,  11,  11])

In [44]:
arr1+arr

array([111, 112, 113, 114, 115,  21,  23,  25,  27,  29,  31])

In [45]:
arr1/arr

array([0.11      , 0.12      , 0.13      , 0.14      , 0.15      ,
       3.2       , 2.83333333, 2.57142857, 2.375     , 2.22222222,
       2.1       ])

In [46]:
arr1/11

array([1.        , 1.09090909, 1.18181818, 1.27272727, 1.36363636,
       1.45454545, 1.54545455, 1.63636364, 1.72727273, 1.81818182,
       1.90909091])

In [47]:
arr1+100

array([111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121])

In [48]:
arr1-100

array([-89, -88, -87, -86, -85, -84, -83, -82, -81, -80, -79])

In [49]:
arr1/0

C:\Users\USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [50]:
0/arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
arr1**3

array([1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859, 8000, 9261],
      dtype=int32)

In [53]:
arr1/9

array([1.22222222, 1.33333333, 1.44444444, 1.55555556, 1.66666667,
       1.77777778, 1.88888889, 2.        , 2.11111111, 2.22222222,
       2.33333333])

In [54]:
np.sqrt(arr1)

array([3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569])

In [55]:
np.exp(arr1)

array([5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
       3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
       1.78482301e+08, 4.85165195e+08, 1.31881573e+09])

In [56]:
np.max(arr1)

21

In [57]:
np.min(arr1)

11